### ISSUE TITLE
Pagination is not working properly (ep. 2)

### ISSUE THREAD

**Issue by Saneesh** [netsensei/cats#1]
Hello Matthias,
This is really great tutorial!
I tried the second tutorial for the pagination. it shows "**pervious 1 next**", but I have many products. Why it is not showing my pages like "**pervious 1 2 3 next**" . The variables like totalItems, itemsPerPage, currentPage are having the values as expected. I have followed the tutorial exactly same but with newer version of the libraries. 

These are the libraries I have used:
ui-bootstrap: 2.1.3
jQuery : 1.10
AngualrJS : 1.3.4

Note: you were using <paginaiton> tag in the template file but in the new version its 

<ul uib-pagination total-items="totalItems" items-per-page"itemsPerPage" ng-model="currentPage" ng-change="pageChanged(currentPage)"></ul>

Any thoughts? I'm really new to AngularJS, do you have any suggestions for it?

**Comment by Saneesh** [comment]
Hello Matthias,
I found the solution! The issue was due to lack of knowledge I have in AngularJS.

```
<div id="products-app" ng-controller="PaginationDemoCtrl">
  <table class="table">
    <tr ng-repeat="row in data.slice(((currentPage - 1) * itemsPerPage), ((currentPage) * itemsPerPage))">
      <!-- <td>{{row.node.name}}</td>
      <td>{{row.node.id}}</td> -->
      <td>{{row.node.title}}</td>
      <td><img ng-src="{{row.node.Image.src}}"></td>
    </tr>
  </table>
  <div class="pagination">
    <ul uib-pagination total-items="totalItems" ng-model="currentPage" ng-change="pageChanged()" class="pagination-sm" items-per-page="itemsPerPage"></ul>
  </div>
</div>
```

```
products.controller('PaginationDemoCtrl', function ($scope, $http) {


  $http.get('/json/products').success(function (result) {
    $scope.data = (function(){
      return result.nodes;
    })();

    $scope.viewby = 2;
    console.log('$scope.data.length: ' + $scope.data.length);

    $scope.totalItems = $scope.data.length;
    $scope.currentPage = 1;
    $scope.itemsPerPage = $scope.viewby;

    // Number of pager buttons to show.
    $scope.maxSize = 1;

    $scope.setPage = function (pageNo) {
      $scope.currentPage = pageNo;
    };

    $scope.pageChanged = function() {
      console.log('Page changed to: ' + $scope.currentPage);
    };

    $scope.setItemsPerPage = function(num) {
      $scope.itemsPerPage = num;

      // Reset to first page.
      $scope.currentPage = 1;
    };
  });
});
```

This is the way I modified the code.
Thanks,
Saneesh.

**Comment by netsensei** [comment]
Hi Saneesh!

Great to read you found a workaround!

I just looked at those version numbers you posted. You use the latest stable Bootstrap UI (2.1.3) with AngularJS 1.3.4.  However, on the [Bootstrap UI website](https://angular-ui.github.io/bootstrap/) I read:

> (**requires AngularJS 1.4.x** or higher, tested with 1.5.8). **0.14.3 is the last version of this library that supports AngularJS 1.3.x** and 0.12.0 is the last version that supports AngularJS 1.2.x.

So, you might also try and test this with a more recent stable version of angular (like 1.5.8 which seems to be the latest stable version in the 1.x branch). This might solve issues with the pagination directive provided by Bootstrap UI not working properly.

With regards,

Matthias.

**Comment by Saneesh** [comment]
Hello Matthias,
Thank you for your time.
Drupal supports(https://www.drupal.org/project/angularjs) 1.3.4 version of Angularjs not the latest.
I tried by loading the latest version of Angularjs manually in drupal, but that also not worked.
Thanks,
Saneesh.
